---
- name: Add Jenkins repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins GPG key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Set Java 21 as default
  alternatives:
    name: java
    path: /usr/lib/jvm/java-21-amazon-corretto/bin/java

- name: Start and enable Jenkins
  service:
    name: jenkins
    state: started
    enabled: yes
